// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImage = `-- name: CreateImage :exec
INSERT INTO images (user_id, filename, file_size, mime, url)
VALUES ($1, $2, $3, $4, $5)
`

type CreateImageParams struct {
	UserID   pgtype.Int8 `json:"user_id"`
	Filename string      `json:"filename"`
	FileSize pgtype.Int8 `json:"file_size"`
	Mime     string      `json:"mime"`
	Url      string      `json:"url"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) error {
	_, err := q.db.Exec(ctx, createImage,
		arg.UserID,
		arg.Filename,
		arg.FileSize,
		arg.Mime,
		arg.Url,
	)
	return err
}
