// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (user_id, filename, file_size, mime)
VALUES ($1, $2, $3, $4)
RETURNING uid
`

type CreateImageParams struct {
	UserID   pgtype.Int8 `json:"user_id"`
	Filename string      `json:"filename"`
	FileSize pgtype.Int8 `json:"file_size"`
	Mime     string      `json:"mime"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createImage,
		arg.UserID,
		arg.Filename,
		arg.FileSize,
		arg.Mime,
	)
	var uid pgtype.UUID
	err := row.Scan(&uid)
	return uid, err
}

const getImage = `-- name: GetImage :one
SELECT uid, images.filename, mime, images.file_size, images.created_at
FROM images
WHERE user_id = $1 AND uid = $2
`

type GetImageParams struct {
	UserID pgtype.Int8 `json:"user_id"`
	Uid    pgtype.UUID `json:"uid"`
}

type GetImageRow struct {
	Uid       pgtype.UUID      `json:"uid"`
	Filename  string           `json:"filename"`
	Mime      string           `json:"mime"`
	FileSize  pgtype.Int8      `json:"file_size"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetImage(ctx context.Context, arg GetImageParams) (GetImageRow, error) {
	row := q.db.QueryRow(ctx, getImage, arg.UserID, arg.Uid)
	var i GetImageRow
	err := row.Scan(
		&i.Uid,
		&i.Filename,
		&i.Mime,
		&i.FileSize,
		&i.CreatedAt,
	)
	return i, err
}

const imageExists = `-- name: ImageExists :one
SELECT
EXISTS(
    SELECT images.uid
    FROM images
    WHERE user_id = $1 AND uid = $2
)
`

type ImageExistsParams struct {
	UserID pgtype.Int8 `json:"user_id"`
	Uid    pgtype.UUID `json:"uid"`
}

func (q *Queries) ImageExists(ctx context.Context, arg ImageExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, imageExists, arg.UserID, arg.Uid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
