// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImage = `-- name: CreateImage :one
INSERT INTO images (user_id, filename, file_size, mime)
VALUES ($1, $2, $3, $4)
RETURNING uid
`

type CreateImageParams struct {
	UserID   pgtype.Int8 `json:"user_id"`
	Filename string      `json:"filename"`
	FileSize pgtype.Int8 `json:"file_size"`
	Mime     string      `json:"mime"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createImage,
		arg.UserID,
		arg.Filename,
		arg.FileSize,
		arg.Mime,
	)
	var uid pgtype.UUID
	err := row.Scan(&uid)
	return uid, err
}
