// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Image struct {
	ID        int64         `json:"id"`
	Url       string        `json:"url"`
	CreatedAt time.Time     `json:"created_at"`
	UserID    sql.NullInt64 `json:"user_id"`
	Uid       uuid.UUID     `json:"uid"`
	Filename  string        `json:"filename"`
	Mime      string        `json:"mime"`
	FileSize  sql.NullInt64 `json:"file_size"`
}

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}
