// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Image struct {
	ID        int64            `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UserID    pgtype.Int8      `json:"user_id"`
	Uid       pgtype.UUID      `json:"uid"`
	Filename  string           `json:"filename"`
	Mime      string           `json:"mime"`
	FileSize  pgtype.Int8      `json:"file_size"`
}

type Transform struct {
	ID            int64            `json:"id"`
	Uuid          pgtype.UUID      `json:"uuid"`
	OriginalImage pgtype.Int8      `json:"original_image"`
	UserID        pgtype.Int8      `json:"user_id"`
	Filename      string           `json:"filename"`
	Mime          string           `json:"mime"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	Status        string           `json:"status"`
}

type User struct {
	ID        int64            `json:"id"`
	Username  string           `json:"username"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
