// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transform.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransform = `-- name: CreateTransform :one
INSERT INTO transform (original_image, user_id)
VALUES ($1, $2)
RETURNING uuid, status
`

type CreateTransformParams struct {
	OriginalImage pgtype.UUID `json:"original_image"`
	UserID        pgtype.Int8 `json:"user_id"`
}

type CreateTransformRow struct {
	Uuid   pgtype.UUID `json:"uuid"`
	Status string      `json:"status"`
}

func (q *Queries) CreateTransform(ctx context.Context, arg CreateTransformParams) (CreateTransformRow, error) {
	row := q.db.QueryRow(ctx, createTransform, arg.OriginalImage, arg.UserID)
	var i CreateTransformRow
	err := row.Scan(&i.Uuid, &i.Status)
	return i, err
}
